<?php
/**
 * This file is part of OXID eShop Community Edition.
 *
 * OXID eShop Community Edition is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OXID eShop Community Edition is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @copyright (C) OXID eSales AG 2003-2016
 * @version   OXID eShop CE
 */
namespace Unit\Core;

use \Exception;
use oxSystemComponentException;
use \oxTestModules;

class ExceptionhandlerTest extends \OxidTestCase
{

    protected $_sMsg = 'TEST_EXCEPTION';

    public function testCallUnExistingMethod()
    {
        $this->setExpectedException('oxSystemComponentException');
        $oExcpHandler = oxNew('oxexceptionhandler');
        $oExcpHandler->__test__();
    }

    public function testSetGetFileName()
    {
        $oTestObject = oxNew('oxexceptionhandler');
        $oTestObject->setLogFileName('TEST.log');
        $this->assertEquals('TEST.log', $oTestObject->getLogFileName());
    }

    // still incomplete
    // We can only test if a log file is written - screen output must be checked manually or with selenium
    public function testExceptionHandlerNotRendererDebug()
    {
        $sFileName = 'oxexceptionhandlerTest_NotRenderer.txt';
        $oExc = oxNew('oxexception', $this->_sMsg);
        $oTestObject = oxNew('oxexceptionhandler', '1'); // iDebug = 1
        $oTestObject->setLogFileName($sFileName);

        try {
            $sMsg = $oTestObject->handleUncaughtException($oExc); // actuall test
            $this->assertNotEquals($this->_sMsg, $sMsg);
        } catch (Exception $e) {
            // Lets try to delete an possible left over file
            if (file_exists($this->getConfig()->getConfigParam('sShopDir') . 'log/' . $sFileName)) {
                unlink($this->getConfig()->getConfigParam('sShopDir') . 'log/' . $sFileName);
            }
            $this->fail('handleUncaughtException() throws an exception.');
        }
        if (!file_exists($this->getConfig()->getConfigParam('sShopDir') . 'log/' . $sFileName)) {
            $this->fail('No debug log file written');
        }
        $sFile = file_get_contents($this->getConfig()->getConfigParam('sShopDir') . 'log/' . $sFileName);
        unlink($this->getConfig()->getConfigParam('sShopDir') . 'log/' . $sFileName); // delete file first as assert may return out this function
        // we check on class name and message - rest is not checked yet
        $this->assertContains($this->_sMsg, $sFile);
        $this->assertContains('oxException', $sFile);
    }

    // We can only test if a log file is not written - screen output must be checked manually or with selenium
    public function testExceptionHandlerNotRendererNoDebug()
    {
        $sFileName = 'oxexceptionhandlerTest_NotRenderer.txt';
        $oExc = oxNew('oxexception', $this->_sMsg);
        $oTestObject = oxNew('oxexceptionhandler');
        $oTestObject->setLogFileName($sFileName);

        try {
            $oTestObject->handleUncaughtException($oExc); // actuall test
        } catch (Exception $e) {
            // Lets try to delete an possible left over file
            if (file_exists($sFileName)) {
                unlink($sFileName);
            }
            $this->fail('handleUncaughtException() throws an exception.');
        }
        if (file_exists($sFileName)) {
            $this->fail('Illegally written in log file.');
            @unlink($sFileName); // delete file first as assert may return out this function
        }
    }

    public function testExceptionHandlerNotRendererDebugNotOxidException()
    {
        $sFileName = 'oxexceptionhandlerTest_NotRenderer.txt';
        $oTestObject = oxNew('oxexceptionhandler', '1'); // iDebug = 1
        $oTestObject->setLogFileName($sFileName);

        $oTestObject->handleUncaughtException(new Exception("test exception"));
        if (!file_exists($this->getConfig()->getConfigParam('sShopDir') . 'log/' . $sFileName)) {
            $this->fail('No debug log file written');
        }
        $sFile = file_get_contents($this->getConfig()->getConfigParam('sShopDir') . 'log/' . $sFileName);
        unlink($this->getConfig()->getConfigParam('sShopDir') . 'log/' . $sFileName); // delete file first as assert may return out this function
        $this->assertContains("test exception", $sFile);
        $this->assertContains('Exception', $sFile);
    }

    public function testSetIDebug()
    {
        $oTestObject = $this->getProxyClass("oxexceptionhandler");
        $oTestObject->setIDebug(2);
        //nothing should happen in unittests
        $this->assertEquals(2, $oTestObject->getNonPublicVar('_iDebug'));
    }

    public function testDealWithNoOxException()
    {
        $oTestObject = $this->getProxyClass("oxexceptionhandler");
        $oTestObject->setIDebug(-1);

        $oTestUtils = $this->getMock("oxUtils", array("writeToLog", "showMessageAndExit", "getTime"));
        $oTestUtils->expects($this->once())->method("writeToLog");
        $oTestException = new Exception("testMsg");

        oxTestModules::addModuleObject('oxUtils', $oTestUtils);

        try {
            $oTestObject->UNITdealWithNoOxException($oTestException);
        } catch (Exception $e) {

        }
    }

}
